name: Daily generate example if new cli was released

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Check for new release, download, run jar, and update last tag
      run: |
        OWNER=flux-capacitor-io
        REPO=flux-cli

        LAST_TAG_FILE=last_release_tag.txt
        LAST_TAG=""
        if [ -f "$LAST_TAG_FILE" ]; then
          LAST_TAG=$(cat $LAST_TAG_FILE)
        fi

        # Get latest release tag
        LATEST_TAG=$(curl -s https://api.github.com/repos/$OWNER/$REPO/releases/latest | jq -r .tag_name)

        if [ "$LATEST_TAG" = "$LAST_TAG" ]; then
          echo "No new release. Last checked: $LAST_TAG"
          exit 0
        fi

        echo "New release found: $LATEST_TAG"

        # Get jar download URL
        ASSET_URL=$(curl -s https://api.github.com/repos/$OWNER/$REPO/releases/tags/$LATEST_TAG \
          | jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url')

        if [ -z "$ASSET_URL" ]; then
          echo "No jar asset found for release $LATEST_TAG"
          exit 1
        fi

        # Download jar
        curl -L -o app.jar "$ASSET_URL"

        # Create flux-kotlin-single project
        rm -rf flux-kotlin-single && java -jar app.jar init --name flux-kotlin-single --template flux-kotlin-single 

        # Save and commit the latest tag
        echo "$LATEST_TAG" > $LAST_TAG_FILE
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        rm app.jar
        git add .
        git commit -m "Generated examples based on flux-cli $LATEST_TAG"
        git push